name: Android
on:
  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    
   # Get flutter dependencies.
    - run: flutter pub get
    
    # Build apk.
    - run: flutter build apk
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@master
      with:
        name: apk-release
        path: build/app/outputs/bundle/release/app-release.apk

    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        node-version: 16
        groups: testers
        file: app/build/outputs/apk/release/app-release-unsigned.apk